In [1]:
import pandas as pd
from scipy.stats import f_oneway
from statsmodels.stats.multicomp import pairwise_tukeyhsd
import matplotlib as mpl
import matplotlib.pyplot as plt
import pandas as pd
from matplotlib.ticker import ScalarFormatter
import numpy as np

In [2]:
def compute_mean_std_table(data: pd.DataFrame, column: str) -> pd.DataFrame:
    return round(
        data.groupby(column)
        .agg(
            {
                "Min Fidelity": ["mean", "std"],
            }
        )
        .rename_axis(column),
        4,
    )


def compute_f_statistic_p_value(
    data: pd.DataFrame, column: str
) -> pd.DataFrame:
    grouped_data = data.groupby(column)

    group_values = [group["Min Fidelity"].values for _, group in grouped_data]

    f_statistic, p_value = f_oneway(*group_values)

    return round(f_statistic, 4), round(p_value, 4)

In [3]:
excel_file_name = './excel_files/hyperparameter_tuning_results_differential_evolution.xlsx'

In [4]:
data = pd.read_excel(excel_file_name)
data = data.round(4)

In [5]:
data.sort_values(by="Min Fidelity", inplace=True, ascending=False)
data.head(3)

,Sequence Length,Population Size,Num Generations,Crossover Rate,Init Sol Type,Differential Weight,Num of Experiments,Min Fidelity,I,X,Y,Z,H,R_X_PI/4
0,4,20,25,0.8,noiseless_ideal,0.45,1000,0.9991,0.9991,0.9993,0.9992,0.9992,0.9991,0.9991
1,4,10,25,0.8,noiseless_ideal,0.45,500,0.9989,0.9989,0.9993,0.9989,0.9991,0.9990,0.9992
2,32,5,25,0.8,noiseless_ideal,0.45,250,0.9984,0.9990,0.9984,0.9989,0.9984,0.9989,0.9986

In [6]:
mean_min_fidelity = round(data["Min Fidelity"].mean(), 4)
std_min_fidelity = round(data["Min Fidelity"].std(), 4)
print(f"Mean min fidelity: {mean_min_fidelity} +- {std_min_fidelity}")

Mean min fidelity: 0.8 +- 0.2656

In [7]:
hyperparameters = [
    "Sequence Length",
    "Population Size",
    "Num Generations",
    "Crossover Rate",
    "Init Sol Type",
    "Differential Weight",
    "Num of Experiments"
]


for hp in hyperparameters:
    display(compute_mean_std_table(data, hp))
    f_statistic, p_value = compute_f_statistic_p_value(data, hp)
    print(f"F-statistic: {f_statistic}, P-value: {p_value}")

                Min Fidelity
                        mean     std
Sequence Length
4                     0.8544  0.1511
8                     0.8636  0.1551
16                    0.8518  0.1770
32                    0.8249  0.2175
64                    0.8106  0.2497
128                   0.7839  0.2825
256                   0.7378  0.3427
512                   0.6732  0.3880

F-statistic: 15.8746, P-value: 0.0

                Min Fidelity
                        mean     std
Population Size
5                     0.7396  0.2897
10                    0.8050  0.2630
20                    0.8554  0.2281

F-statistic: 31.9696, P-value: 0.0

                Min Fidelity
                        mean     std
Num Generations
6                     0.7219  0.3142
13                    0.8056  0.2513
25                    0.8726  0.1964

F-statistic: 55.2934, P-value: 0.0

               Min Fidelity
                       mean     std
Crossover Rate
0.2                  0.7638  0.3083
0.4                  0.8011  0.2596
0.8                  0.8352  0.2165

F-statistic: 11.8395, P-value: 0.0

                Min Fidelity
                        mean     std
Init Sol Type
noiseless_ideal       0.9700  0.0283
normal_distro         0.5853  0.3534
uniform_distro        0.8448  0.0954

F-statistic: 555.1424, P-value: 0.0

                    Min Fidelity
                            mean     std
Differential Weight
0.45                      0.7253  0.3502
0.90                      0.8097  0.2441
1.80                      0.8651  0.1403

F-statistic: 47.7245, P-value: 0.0

                   Min Fidelity
                           mean     std
Num of Experiments
60                       0.6558  0.3290
120                      0.7203  0.3163
130                      0.7422  0.2736
240                      0.7895  0.2824
250                      0.8208  0.2361
260                      0.8107  0.2503
500                      0.8841  0.1784
520                      0.8640  0.2123
1000                     0.9128  0.1550

F-statistic: 22.9674, P-value: 0.0

In [8]:
use_pdf = True
use_png = not use_pdf
if use_pdf:
    mpl.use("pdf")
file_extension = "pdf" if use_pdf else "png"

In [9]:
report_path= "/home/chriswise/github/Honours-Research-ML-for-QC/Report/sections/grad_free_results/figures/"
windows_path = "/mnt/c/Users/ChrisWiseLocal/OneDrive/Documents/Uni/UNSW/2023/Honours Research/Seminars/report_photos/"

In [10]:
path_to_save = report_path if use_pdf else windows_path

In [11]:
width = 3.487
height = width / 1.618
alpha_value = 0.75
title_font_size = 9
plt.rc("font", family="serif", serif="cm10")
plt.rc("text", usetex=True)
plt.rc("axes", labelsize=title_font_size - 2)

In [12]:
mean_min_fidelity = data.groupby("Sequence Length")["Min Fidelity"].mean()

In [13]:
print(sorted(data["Sequence Length"].unique()))

[4, 8, 16, 32, 64, 128, 256, 512]

In [14]:
default_blue = plt.rcParams['axes.prop_cycle'].by_key()['color'][0]

In [15]:
# width as measured in inkscape
width = 3.487
height = width / 1.618
alpha_value = 0.85
title_font_size = 9

fig, ax = plt.subplots(figsize=(width, height))

plt.rc("font", family="serif", serif="Times")
plt.rc("text", usetex=True)
plt.rc("axes", labelsize=title_font_size - 2)

plt.suptitle(
    "Mean Minimum Fidelity for Sequence Lengths (Differential Evolution)",
    fontsize=title_font_size,
)

sequence_lengths = sorted(data["Sequence Length"].unique())

mean_min_fidelity = data.groupby("Sequence Length")["Min Fidelity"].mean()
std_min_fidelity = data.groupby("Sequence Length")["Min Fidelity"].std()

upper_bounds = np.clip(mean_min_fidelity + std_min_fidelity, 0, 1)
lower_bounds = np.clip(mean_min_fidelity - std_min_fidelity, 0, 1)

corrected_std_positive = upper_bounds - mean_min_fidelity
corrected_std_negative = mean_min_fidelity - lower_bounds

ax.plot(sequence_lengths, mean_min_fidelity, color=default_blue, alpha=alpha_value)
ax.errorbar(
    sequence_lengths,
    mean_min_fidelity,
    yerr=[corrected_std_negative, corrected_std_positive],
    fmt=".",
    capsize=2,
    capthick=1,
    color=default_blue,
    alpha=alpha_value,
)
ax.set_xscale("log", base=2)

plt.xticks(sequence_lengths, fontsize=title_font_size - 2)
plt.yticks(fontsize=title_font_size - 2)

plt.xlabel("Sequence Length", fontsize=title_font_size - 2)
plt.ylabel("Mean Minimum Fidelity", fontsize=title_font_size - 2)
plt.ylim(-0.1, 1.1)

formatter = ScalarFormatter()
formatter.set_scientific(False)
ax.xaxis.set_major_formatter(formatter)


# fig.tight_layout()
plt.savefig(
    path_to_save + f"de_results_sequence_length.{file_extension}",
    dpi=500,
    bbox_inches="tight",
)
# plt.show()

In [16]:
# width as measured in inkscape
width = 3.487
height = width / 1.618
alpha_value = 0.85
title_font_size = 9

fig, ax = plt.subplots(figsize=(width, height))

plt.rc("font", family="serif", serif="Times")
plt.rc("text", usetex=True)
plt.rc("axes", labelsize=title_font_size - 2)

plt.suptitle(
    "Mean Minimum Fidelity for Experiments Performed (Differential Evolution)",
    fontsize=title_font_size,
)

num_experiments = sorted(data["Num of Experiments"].unique())

mean_min_fidelity = data.groupby("Num of Experiments")["Min Fidelity"].mean()
std_min_fidelity = data.groupby("Num of Experiments")["Min Fidelity"].std()

upper_bounds = np.clip(mean_min_fidelity + std_min_fidelity, 0, 1)
lower_bounds = np.clip(mean_min_fidelity - std_min_fidelity, 0, 1)

corrected_std_positive = upper_bounds - mean_min_fidelity
corrected_std_negative = mean_min_fidelity - lower_bounds

ax.plot(
    num_experiments, mean_min_fidelity, color=default_blue, alpha=alpha_value
)
ax.errorbar(
    num_experiments,
    mean_min_fidelity,
    yerr=[corrected_std_negative, corrected_std_positive],
    fmt=".",
    capsize=2,
    capthick=1,
    color=default_blue,
    alpha=alpha_value,
)

# ax.set_xscale("log", base=2)
plt.xticks([100 * x for x in range(0, 11)], fontsize=title_font_size - 2)
plt.yticks(fontsize=title_font_size - 2)

plt.xlabel("Relative Number of Experiments Performed", fontsize=title_font_size - 2)
plt.ylabel("Mean Minimum Fidelity", fontsize=title_font_size - 2)
plt.ylim(-0.1, 1.1)

formatter = ScalarFormatter()
formatter.set_scientific(False)
ax.xaxis.set_major_formatter(formatter)


# fig.tight_layout()
plt.savefig(
    path_to_save + f"de_results_num_experiments.{file_extension}",
    dpi=500,
    bbox_inches="tight",
)
# plt.show()